name: 'rec2 history'
run-name: 'Check rec2 commit history'

on:
  workflow_dispatch:
    inputs:
      rec2-ref:
        description: 'rec2 ref'

jobs:
  build:
    name: ${{ matrix.platform.what }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: MinGW,  os: ubuntu-latest,  what: mingw,  ninja: true }
          - { name: MSVC,   os: windows-latest, what: msvc,   ninja: true, msvc: true }
          - { name: MinGW,  os: ubuntu-latest,  what: checks }
    steps:
      - name: 'Checkout rec2_bisect'
        uses: actions/checkout@v4
      - name: 'Install Mingw toolchain'
        if: ${{ matrix.platform == 'mingw' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64 g++-mingw-w64
      - name: 'Configure vcvars x86'
        if: ${{ matrix.platform == 'msvc' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64_x86  # host: x64 target: x86
      - name: Set up ninja
        if: ${{ matrix.platform.ninja }}
        uses: ./.github/actions/setup-ninja
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: 'Checkout rec2'
        uses: actions/checkout@v4
        with:
          repository: madebr/rec2
          ref: ${{ inputs.rec2-ref || 'master' }}
          submodules: recursive
          fetch-depth: 0
          path: rec2
      - name: 'Build rec2 history'
        shell: sh
        run: |
          initial_commit=$(git -C rec2 log --grep="Initial commit" --pretty="%H")
          git -C rec2 log --pretty="%H %s" >rec2_commits.txt
          python scripts/build_history.py \
            --source rec2 \
            --build rec2-build \
            --commits rec2_commits.txt \
            --log build.log \
            --what ${{ matrix.platform.what }}
      - name: 'Cat build.log'
        shell: sh
        run: |
          cat build.log
      - name: 'Upload log'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.what }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/rec2_commits.txt
            ${{ github.workspace }}/build.log
